-- Limpiar la tabla para el despliegue masivo
TRUNCATE TABLE estudiantes RESTART IDENTITY;

-- Inserción masiva de 100 registros académicos
INSERT INTO estudiantes (nombre, materia, nota) VALUES
('Jean Pierre Mora', 'Arquitectura Cloud', 9.50),
('Carlos Andrade', 'Arquitectura Cloud', 8.20),
('María José Benítez', 'Arquitectura Cloud', 4.50),
('Anahí Cisneros', 'SRE & Observabilidad', 9.80),
('Kevin Espinosa', 'SRE & Observabilidad', 6.00),
('Luis Fernando Gómez', 'SRE & Observabilidad', 7.10),
('Diana Gutiérrez', 'Desarrollo Web Fullstack', 8.90),
('Bryan Jacome', 'Desarrollo Web Fullstack', 5.50),
('Mateo López', 'Desarrollo Web Fullstack', 10.00),
('Paola Ortega', 'Bases de Datos II', 6.80),
('Alejandro Pazmiño', 'Bases de Datos II', 3.20),
('Sonia Quishpe', 'Bases de Datos II', 8.00),
('Roberto Toapanta', 'Sistemas Operativos', 7.50),
('Valeria Valencia', 'Sistemas Operativos', 5.90),
('William Zambrano', 'Sistemas Operativos', 9.00),
('Alejandra Aguirre', 'Arquitectura Cloud', 8.70),
('Andrés Alvear', 'SRE & Observabilidad', 6.20),
('Beatriz Barahona', 'Desarrollo Web Fullstack', 7.80),
('Christian Bustamante', 'Bases de Datos II', 5.10),
('Daniela Cárdenas', 'Sistemas Operativos', 9.30),
('Édison Cevallos', 'Arquitectura Cloud', 4.80),
('Fabiola Dávila', 'SRE & Observabilidad', 8.00),
('Gabriel Erazo', 'Desarrollo Web Fullstack', 6.90),
('Gabriela Espinoza', 'Bases de Datos II', 7.20),
('Hugo Flores', 'Sistemas Operativos', 5.40),
('Isabel Franco', 'Arquitectura Cloud', 9.10),
('Jaime Freire', 'SRE & Observabilidad', 6.50),
('Karla Galarza', 'Desarrollo Web Fullstack', 8.30),
('Leonardo Garzón', 'Bases de Datos II', 3.90),
('Lorena Guerrero', 'Sistemas Operativos', 7.00),
('Manuel Heredia', 'Arquitectura Cloud', 8.10),
('Mónica Herrera', 'SRE & Observabilidad', 5.80),
('Nelson Jaramillo', 'Desarrollo Web Fullstack', 9.60),
('Olga Jiménez', 'Bases de Datos II', 7.40),
('Patricio Lara', 'Sistemas Operativos', 4.20),
('Ramiro León', 'Arquitectura Cloud', 6.70),
('Sandra Maldonado', 'SRE & Observabilidad', 8.50),
('Santiago Medina', 'Desarrollo Web Fullstack', 7.90),
('Tatiana Mendoza', 'Bases de Datos II', 6.10),
('Víctor Miranda', 'Sistemas Operativos', 9.20),
('Yolanda Moncayo', 'Arquitectura Cloud', 5.30),
('Álex Morales', 'SRE & Observabilidad', 7.60),
('Alicia Moreno', 'Desarrollo Web Fullstack', 8.80),
('Arturo Muñoz', 'Bases de Datos II', 4.70),
('Bárbara Narváez', 'Sistemas Operativos', 6.40),
('César Navas', 'Arquitectura Cloud', 9.00),
('Cristina Ochoa', 'SRE & Observabilidad', 8.20),
('Diego Ortiz', 'Desarrollo Web Fullstack', 5.00),
('Elena Pacheco', 'Bases de Datos II', 7.70),
('Enrique Palacios', 'Sistemas Operativos', 6.30),
('Fernando Paredes', 'Arquitectura Cloud', 8.40),
('Gisela Peña', 'SRE & Observabilidad', 3.50),
('Gonzalo Pesántez', 'Desarrollo Web Fullstack', 9.70),
('Irene Pinto', 'Bases de Datos II', 7.10),
('Iván Plaza', 'Sistemas Operativos', 5.60),
('Javier Ponce', 'Arquitectura Cloud', 8.90),
('Jessica Reinoso', 'SRE & Observabilidad', 6.60),
('Jorge Riofrío', 'Desarrollo Web Fullstack', 7.30),
('Juana Rivas', 'Bases de Datos II', 4.10),
('Julio Rivera', 'Sistemas Operativos', 8.60),
('Lourdes Rodríguez', 'Arquitectura Cloud', 9.40),
('Lucas Rojas', 'SRE & Observabilidad', 5.20),
('Lucía Romero', 'Desarrollo Web Fullstack', 7.50),
('Luis Rosales', 'Bases de Datos II', 6.80),
('Magdalena Ruiz', 'Sistemas Operativos', 9.90),
('Marco Salazar', 'Arquitectura Cloud', 4.90),
('Margarita Salinas', 'SRE & Observabilidad', 8.30),
('Martha Sanchéz', 'Desarrollo Web Fullstack', 6.70),
('Martín Sandoval', 'Bases de Datos II', 7.80),
('Mercedes Segura', 'Sistemas Operativos', 5.70),
('Miguel Silva', 'Arquitectura Cloud', 8.00),
('Miriam Solano', 'SRE & Observabilidad', 9.10),
('Nancy Solís', 'Desarrollo Web Fullstack', 3.80),
('Óscar Suárez', 'Bases de Datos II', 7.40),
('Pablo Terán', 'Sistemas Operativos', 6.50),
('Patricia Torres', 'Arquitectura Cloud', 8.60),
('Paúl Vacacela', 'SRE & Observabilidad', 5.90),
('Pedro Valdivieso', 'Desarrollo Web Fullstack', 9.20),
('Rafael Valencia', 'Bases de Datos II', 7.00),
('Raúl Vallejo', 'Sistemas Operativos', 4.40),
('René Vargas', 'Arquitectura Cloud', 7.90),
('Ricardo Vasconez', 'SRE & Observabilidad', 8.40),
('Rosa Vega', 'Desarrollo Web Fullstack', 6.20),
('Rubén Velasco', 'Bases de Datos II', 9.50),
('Sara Véliz', 'Sistemas Operativos', 5.10),
('Silvia Vera', 'Arquitectura Cloud', 7.30),
('Stalin Vinueza', 'SRE & Observabilidad', 8.80),
('Susana Yánez', 'Desarrollo Web Fullstack', 4.60),
('Xavier Yepez', 'Bases de Datos II', 6.90),
('Zhandling Zambrano', 'Sistemas Operativos', 8.10),
('Adriana Zurita', 'Arquitectura Cloud', 9.00),
('Agustín Cárdenas', 'SRE & Observabilidad', 5.50),
('Amparo Almeida', 'Desarrollo Web Fullstack', 7.70),
('Bairon Franco', 'Bases de Datos II', 3.20),
('Camila Ibarra', 'Sistemas Operativos', 8.40),
('Darío Lozano', 'Arquitectura Cloud', 6.30),
('Estefanía Merchán', 'SRE & Observabilidad', 9.70),
('Freddy Noboa', 'Desarrollo Web Fullstack', 7.20),
('Gladys Paguay', 'Bases de Datos II', 5.80),
('Israel Sarango', 'Sistemas Operativos', 8.00);
